server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET}  # Replace with your Keycloak client secret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
           # redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/handleliste
web:
  security:
    csrf:
      enabled: false # Disable CSRF for testing; re-enable for production